name: go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make
      
    - name: Run unit tests
      run: make test


  verify:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
            
    - name: Run Verify Checks
      run: make verify

    - name: Export Unit Test Coverage Report
      run: make export-coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}